   ------- 카테고리별 판매 금액 --------
   SELECT PRODUCT.CATEGORY, SUM(PRODUCT.PRICE * ORDER_DETAIL.OD_CNT)
   FROM PRODUCT, ORDER_DETAIL 
   WHERE PRODUCT.P_NO = ORDER_DETAIL.P_NO 
   GROUP BY PRODUCT.CATEGORY
   -------------------------------
   
   
   SELECT PRODUCT.CATEGORY FROM PRODUCT OUTER JOIN ORDER_INFO
   ON PRODUCT.P_NO =
   
   SELECT PRODUCT.CATEGORY,  PRODUCT.PRICE * ORDER_DETAIL.OD_CNT
   FROM PRODUCT, ORDER_DETAIL 
   WHERE PRODUCT.P_NO = ORDER_DETAIL.P_NO 
   GROUP BY PRODUCT.CATEGORY, PRODUCT.PRICE * ORDER_DETAIL.OD_CNT
   
   보여줘 뭘? 카테고리랑 총 가격을 
   어디서? 프로덕트랑, 오더 디테일에서
   프로덕트의 상품 번호랑, 오더 디테일에서 상품 번호랑 일치하면
   
   
   
   SELECT PRODUCT.P_NO,P_NM,PRICE,P_IMG_URL,CATEGORY, SUM(OD_CNT) 
   FROM ORDER_DETAIL 
   INNER JOIN PRODUCT 
   ON ORDER_DETAIL.P_NO = PRODUCT.P_NO
   GROUP BY PRODUCT.P_NO,P_NM,PRICE,P_IMG_URL,CATEGORY 
   ORDER BY SUM(OD_CNT) DESC
   

   SELECT * FROM ORDER_DETAIL
   
   
   
   DELETE FROM ORDER_DETAIL
   
   DELETE FROM ORDER_INFO
   
   DELETE FROM PRODUCT

      SELECT * FROM PRODUCT ORDER BY P_NO ASC
   
      SELECT * FROM ORDER_DETAIL ORDER BY OD_NO ASC 
      
      SELECT * FROM ORDER_INFO ORDER BY O_NO ASC 
      
      SELECT * FROM ORDER_INFO ORDER BY ASC 
      
      

SELECT * FROM ORDER_INFO ORDER BY O_NO ASC;


SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM ORDER_INFO;

SELECT * FROM ORDER_INFO

      SELECT * FROM PRODUCT, ORDER_DETAIL WHERE PRODUCT.P_NO = ORDER_DETAIL.P_NO
     